apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: custom-metrics-collection
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql

